# Generated by Django 3.0.5 on 2020-05-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_dislikes',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='movie_likes',
        ),
    ]
