# Generated by Django 3.0.5 on 2020-05-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200521_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_genres',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
