# Generated by Django 3.0.5 on 2020-05-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200521_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movie_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='movie_dislikes',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='movie_genres',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='movie_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='movie_title',
            new_name='title',
        ),
    ]
